# Generated by Django 5.0.6 on 2024-09-16 20:20

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
            ],
            options={
                "db_table": "MAE_CHAT",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=100)),
                ("image", models.ImageField(upload_to="group/%Y/%m/%d/")),
            ],
            options={
                "db_table": "MAE_GROUP",
            },
        ),
        migrations.CreateModel(
            name="ConnectionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "On-line"),
                            ("offline", "Off-line"),
                            ("away", "Away"),
                        ],
                        db_column="status",
                        default="online",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "MAE_CONNECTION_HISTORY",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                ("content", models.TextField(db_column="content")),
                ("sent_at", models.DateField(auto_now_add=True, db_column="sent_at")),
                (
                    "deliverated",
                    models.BooleanField(db_column="deliverated", default=False),
                ),
                ("seen", models.BooleanField(db_column="seen", default=False)),
                (
                    "id_chat",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_chat",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mschatroom.chat",
                    ),
                ),
                (
                    "id_group",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_group",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mschatroom.group",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        db_column="id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "MAE_MESSAGE",
            },
        ),
        migrations.CreateModel(
            name="UserChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "id_chat",
                    models.ForeignKey(
                        db_column="id_chat",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mschatroom.chat",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        db_column="id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "MAE_USER_CHAT",
            },
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "id_group",
                    models.ForeignKey(
                        db_column="id_group",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mschatroom.group",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        db_column="id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "MAE_USER_GROUP",
            },
        ),
    ]
